#!/usr/bin/env bash
# Regenerates master.css by concatenating the vendor/theme CSS chain that
# used to be loaded via runtime @import (13 sequential round-trips before
# first paint — see web-optimization-sop docs/02-performance.md).
#
# Source files stay untouched and individually addressable in css/ and
# style.css so Renovate can keep bumping vendored files independently;
# this script just re-flattens them into one shippable file after any
# source file changes. No bundler/build system is introduced — this is
# a plain concatenation, matching the site's "hand-authored, no build
# step" convention (CLAUDE.md).
#
# Run from repo root: ./scripts/build-css.sh

set -euo pipefail
cd "$(dirname "$0")/.."

OUT=master.css
SOURCES=(
  css/bootstrap.min.css
  css/font-awesome.min.css
  css/owl.carousel.css
  css/heading.css
  css/magnific-popup.css
  css/owl.theme.css
  css/owl.transitions.css
  css/nivo-slider.css
  css/animate.css
  css/meanmenu.min.css
  css/main.css
  style.css
  css/interior-pages.css
  css/responsive.css
)

{
  echo "/* AUTO-GENERATED by scripts/build-css.sh — do not hand-edit."
  echo " * Edit the source files listed in this script, then re-run it."
  echo " * Concatenation order matches the original @import chain in git history. */"
  for f in "${SOURCES[@]}"; do
    echo ""
    echo "/* ---- source: $f ---- */"
    if [[ "$f" == css/* ]]; then
      # url(...) refs inside css/*.css were relative to css/; master.css
      # now lives at repo root, one level up — rewrite bare and ../-relative
      # url() paths accordingly so fonts/images still resolve.
      sed -E "s#url\(([\"']?)\.\./#url(\1#g; s#url\((['\"]?)([A-Za-z0-9_.-]+\.(png|gif|jpg|jpeg|svg))#url(\1css/\2#g" "$f"
    else
      cat "$f"
    fi
  done
} > "$OUT"

echo "Wrote $OUT ($(wc -c < "$OUT") bytes) from ${#SOURCES[@]} source files."
