#!/usr/bin/env bash
# Regenerates master.css by concatenating the vendor/theme CSS chain that
# used to be loaded via runtime @import (13 sequential round-trips before
# first paint — see web-optimization-sop docs/02-performance.md).
#
# Source files stay untouched and individually addressable in css/ and
# style.css so Renovate can keep bumping vendored files independently;
# this script just re-flattens them into one shippable file after any
# source file changes. No bundler/build system is introduced — this is
# a plain concatenation, matching the site's "hand-authored, no build
# step" convention (CLAUDE.md).
#
# Run from repo root: ./scripts/build-css.sh

set -euo pipefail
cd "$(dirname "$0")/.."

OUT=master.css
SOURCES=(
  css/bootstrap.min.css
  css/font-awesome.min.css
  css/heading.css
  css/animate.css
  css/main.css
  style.css
  css/interior-pages.css
  css/responsive.css
)

TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT

{
  for f in "${SOURCES[@]}"; do
    echo ""
    echo "/* ---- source: $f ---- */"
    if [[ "$f" == css/* ]]; then
      # url(...) refs inside css/*.css were relative to css/; master.css
      # now lives at repo root, one level up — rewrite bare and ../-relative
      # url() paths accordingly so fonts/images still resolve.
      sed -E "s#url\(([\"']?)\.\./#url(\1#g; s#url\((['\"]?)([A-Za-z0-9_.-]+\.(png|gif|jpg|jpeg|svg))#url(\1css/\2#g" "$f"
    else
      cat "$f"
    fi
  done
} > "$TMP"

# Minified via clean-css-cli (npx) — cuts the shipped payload without
# introducing a persistent bundler/build system; this is a one-shot CLI
# pass over the already-flattened file, same category of tool as the
# pyftsubset/glyphhanger commands used elsewhere in this program.
echo "/*! AUTO-GENERATED by scripts/build-css.sh — do not hand-edit. Edit the source files listed in this script, then re-run it. */" > "$OUT"
npx --yes clean-css-cli "$TMP" >> "$OUT"

echo "Wrote $OUT ($(wc -c < "$OUT") bytes, minified) from ${#SOURCES[@]} source files."
